added input check in whitelisting

diff --git a/roles/pre-ansimail/files/ansimail_scripts/whitelist-bigmailer b/roles/pre-ansimail/files/ansimail_scripts/whitelist-bigmailer
--- a/roles/pre-ansimail/files/ansimail_scripts/whitelist-bigmailer
+++ b/roles/pre-ansimail/files/ansimail_scripts/whitelist-bigmailer
@@ -1,11 +1,11 @@
 #!/bin/sh
 
-if [ "$(id -u)" -ne 0 ]; then
-        echo "This can only be run by root"
-        exit 1
-fi
-
 . /usr/local/lib/ansimail/helpers/variables
+
+if [ "$#" -eq 0 ]; then
+	echo "Error: no big mailer domain specified"
+	exit 255
+fi
 
 domain="$1"
 bigmailers="$spam_home/bigmailer-names"
